### ISSUE TITLE
About getting results from wandb

### ISSUE THREAD

**Issue by wyiguanw** [mikeqzy/3dgs-avatar-release#4]
hello, thanks for your work. I encountered an issue with rasterization during training. I get this error:

Error executing job with overrides: ['dataset=zjumocap_377_mono']
Traceback (most recent call last):
  File "train.py", line 327, in main
    training(config)
  File "train.py", line 107, in training
    render_pkg = render(data, iteration, scene, pipe, background, compute_loss=True, return_opacity=use_mask)
  File "/home/zilongwang/Research/Diffusion_Human/3dgs-avatar-release/gaussian_renderer/__init__.py", line 100, in render
    cov3D_precomp=cov3D_precomp)
  File "/home/zilongwang/mambaforge/envs/3dgs-avatar/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zilongwang/mambaforge/envs/3dgs-avatar/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 219, in forward
    raster_settings,
  File "/home/zilongwang/mambaforge/envs/3dgs-avatar/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 41, in rasterize_gaussians
    raster_settings,
  File "/home/zilongwang/mambaforge/envs/3dgs-avatar/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 92, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: numel: integer multiplication overflow

do you have any idea why this happened and how to fix it?

thanks

**Comment by mikeqzy** [comment]
Hi,
The error didn't seem related to wandb logging. Did you pip install the `diff_gaussian_rasterization` module successfully? If so, can you please provide more information on your training script and configs?
